name: Pylint

on: pull_request

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint
        pip install pytest
    - name: Analysing the code with Pylint
      run: |
        pylint $(git ls-files '*.py') --fail-under 9 --ignored-modules config --ignore config.py --disable=W0511,W0718,R0903
    - name: Execute unit tests with Pytest
      run: |
        pytest $(git ls-files 'test_*.py')
        